---
language: python
cache:
  - pip
  - directories:
      - "node_modules"
      - $HOME/.cache
os:
  - linux
stages:
  - phase1
before_install:
  - nvm install $TRAVIS_NODE_VERSION
  - >
    which tox >/dev/null ||
    if [ -z ${VIRTUAL_ENV+x} ];
    then python -m pip install --user tox tox-pyenv;
    else python -m pip install tox tox-pyenv twine;
    fi
notifications:
  email:
    - sorin.sbarnea@gmail.com
jobs:
  include:
    - stage: phase1
      script:
        # package building added here purely to fail-fast if is broken
        - python setup.py sdist bdist_wheel
        - python -m tox
      env: TOXENV=linters
      python: "2.7"
      language: nodejs
      node_js:
        - "8"
env:
  global:
    - PIP_DISABLE_PIP_VERSION_CHECK=1
    - TRAVIS_NODE_VERSION="v8.11.3"
