---
- project:
    templates:
      - nodejs4-jobs
    # bionic needed for less ancient nodejs/npm
    nodeset: ubuntu-bionic
    check:
      jobs:
        - openstack-tox-linters
    gate:
      jobs:
        - openstack-tox-linters
