---
- job:
    name: openstack-tox-linters-npm
    parent: openstack-tox-linters
    # bionic needed for less ancient nodejs/npm which would fail to install
    # cspell regardless engines mentioned in package.json
    nodeset: ubuntu-bionic

- project:
    check:
      jobs:
        - openstack-tox-linters-npm
    gate:
      jobs:
        - openstack-tox-linters-npm
